descriptions:
  - key: base
    description: |
      You are given a server access log at logs/access.log in Common Log Format (CLF).
      Produce a plain-text summary file named summary.txt in the task root (/app):
      - total_requests: total number of log lines
      - unique_ips: number of unique client IPs
      - top_ip: the IP with the highest request count
      - num_4xx: count of responses with status codes 400?499
      - num_5xx: count of responses with status codes 500?599
      - top_endpoint: most requested path portion of the request (ignore query strings)

      Formatting requirements for summary.txt (exact keys, lowercase, one per line):
      total_requests=<int>
      unique_ips=<int>
      top_ip=<ip>
      num_4xx=<int>
      num_5xx=<int>
      top_endpoint=<path>

      Rules:
      - Parse only the provided file logs/access.log; do not download anything.
      - Treat multiple requests to the same path with different queries as the same endpoint.
      - Break ties by lexicographically smallest value for top_ip and top_endpoint.
      - Write the output to summary.txt in the current working directory.
      - You may use standard shell utilities available in Ubuntu (awk/sed/grep/sort/uniq).
author_email: your@email.com
difficulty: medium
tags:
  - logs
  - awk
  - linux
max_agent_timeout_sec: 300
max_test_timeout_sec: 60
test_scripts:
  - setup-uv-pytest.sh
  - run-uv-pytest.sh
run_tests_in_same_shell: true
